name: "Build & Deploy Page"
on:
  push:
    branches:
      - main
  schedule:
   # Run every morning to ensure component documentation is up to date on deployment
   - cron: '23 5 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
        install_extensions: false
        deploy: true
